name: swiftdrop_customer_app
description: SwiftDrop — UK delivery platform customer app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_storage: ^2.1.1
  dio: ^5.4.3
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.2
  flutter_local_notifications: ^17.1.2
  flutter_dotenv: ^5.1.0
  connectivity_plus: ^6.0.3
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  geolocator: ^12.0.0
  google_maps_flutter: ^2.7.0
  permission_handler: ^11.3.1
  logger: ^2.3.0
  intl: ^0.19.0
  google_fonts: ^6.2.1
  country_picker: ^2.0.27
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/appIcon.jpg"
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "assets/icons/appIcon.jpg"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/animations/
